### ISSUE TITLE
Some errors of SpeedTreeHDRP_ASE.shader

### ISSUE THREAD

**Issue by phishchiang** [VergilUa/SpeedTreev6HDRP_ASE_Port#3] opened 2021-08-20 06:44 UTC
Hi, 
I installed ASE in the HDRP demo project before import the shader, then it has some weird rendering issues in the scene.
The material looks almost like a mirror that reflected the environment strangely. 
Here are some of the error messages from SpeedTreeHDRP_ASE.shader
```
Shader error in 'Nature/SpeedTreeHDRP_ASE': 'GetDecalSurfaceData': cannot convert from 'float' to 'struct FragInputs' at line 639 (on d3d11)
Shader error in 'Nature/SpeedTreeHDRP_ASE': undeclared identifier 'IsGammaSpace' at line 1150 (on d3d11)
```

**Unity** : 2020.3.8f1
**HDRP** : 10.2.1
**ASE** : 1.8.9.012

This is the screenshot of the error message :
 ![Capture_113](https://user-images.githubusercontent.com/19939220/130191093-e51a0c6c-c071-4de5-bd39-67a41335d93a.JPG)

Thank you in advance, please let me know if you have any ideas.

**Comment by VergilUa** [comment] 2021-08-20 06:51
Hi, this is most likely due to HDRP version difference. Try re-saving shader from the ASE editor, see if it helps.
Last pushed shader version is for 10.5.0, so alternatively, you can try upgrading HDRP package.

**Comment by phishchiang** [comment] 2021-08-20 08:14
Hi @VergilUa,
Re-saving definitely works on my end, much appreciated! :bow:
The only thing that bugs me is the shadow seems to not support the alpha shape from the leaves material.
![Capture_114](https://user-images.githubusercontent.com/19939220/130202334-61188681-3c10-4e1b-af73-57768f679f96.JPG)
Is this also a way to resolve?
Thank you.

**Comment by VergilUa** [comment] 2021-08-20 08:24
Hmm, some outputs maybe got disconnected? Not sure.
Check if outputs are correct, Alpha and Alpha Clip Threshold.

Also check if alpha clipping is enabled. Try disabling / re-enabling it back again and reconnecting outputs.
![image](https://user-images.githubusercontent.com/24496266/130203389-2dcce8bb-67ed-48f2-aebe-be0ed5aa089b.png)
![image](https://user-images.githubusercontent.com/24496266/130203751-79be395b-225e-4065-980d-8822e785a843.png)

**Comment by phishchiang** [comment] 2021-08-23 07:33
Hi @VergilUa ,
um...the shadow issue remains the same even if I start a new project and make sure all the settings match yours.
(The only difference is SpecularOcculusion, but also tried default and yours)
Not sure if the error messages help:
`ArgumentException: Requested value 'AsIs' was not found.`
![Capture_126](https://user-images.githubusercontent.com/19939220/130407999-67a11565-9394-4bd8-85bb-8c20f094493c.JPG)
Thank you

**Comment by VergilUa** [comment] 2021-08-23 08:00
Hi, try ASE 1.8.8 as well. Perhaps they've changed something in template.
If you haven't rolled back shader after upgrading to 10.5, try one that is in the repo.

**Comment by VergilUa** [comment] 2021-08-23 08:09
Nvm, I've just checked ASE 1.8.9 on 10.5 and shadow transparency's looking fine:
![image](https://user-images.githubusercontent.com/24496266/130412858-49d66bc4-9968-4f6c-8aac-70e942795ebe.png)

Perhaphs something is wrong with shadow / light settings?

Edit:
Alternatively, send me a minimal reproduction / project. I'll look into it.

**Comment by VergilUa** [comment] 2021-08-23 08:44
@phishchiang I've reproduced it in clean project.
Select pine materials in project view, one by one (without multiple selection) and it should fix itself.
(make sure you're using shader and inspector from the master branch, not the package version)

![image](https://user-images.githubusercontent.com/24496266/130417693-f2649a44-c7bd-4dba-b79c-9f9174361a7c.png)
Problem is that sample tree package was made a while ago, and it doesn't have keywords enabled by default, that came later on with inspector changes.

Selecting materials should trigger inspector to enable required keywords on the material automatically.
I really should update unitypackages, as they're kinda obsolete now.

**Comment by VergilUa** [comment] 2021-08-23 09:58
Updated packages with newer version for the shader + inspector, as well as pine example package.
Should be fixed now. Let me know if those work for you, I'll update the issue.

**Comment by phishchiang** [comment] 2021-08-24 06:17
@VergilUa Wow, it works!!!
Thank you so much and how you respond so fast every time.
This is really a magic trick that by selecting the leave material in order to work. 
Awesome!!🙇‍♂️👍🎉

**Comment by VergilUa** [comment] 2021-08-24 08:04
Glad it helped :)
Anyway, this shouldn't be an issue with newer example package, so I'll close this issue.

**Closed as completed by VergilUa** 2021-08-24 08:04 UTC
